name: mls_studio
description: 'Music Lesson Studio UI'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  libtab: ^0.0.9
  #    path: ../../libtab
  mls_api:
    path: ../packages/api_client
  mls_testing_create_auth_token:
    path: ../packages/create_auth_token
  web: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  meta: ^1.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/arrow_45.svg
    - assets/arrow_135.svg
    - assets/arrow_horizontal.svg
    - assets/arrow_vertical.svg
