name: Flutter build android
run-name: ${{ inputs.flutter_package }} build android

on:
  workflow_call:
    inputs:
      flutter_package:
        description: Path from repository root to Flutter package
        type: string
        required: true

env:
  flutter_version: 3.41.8

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'oracle'
      - uses: android-actions/setup-android@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: 'stable'
      - name: build
        run: flutter build appbundle
        working-directory: ${{ inputs.flutter_package }}
