name: Flutter integration test
run-name: ${{ inputs.flutter_package }} integration test

on:
  workflow_call:
    inputs:
      flutter_package:
        description: Path from repository root to Flutter package
        type: string
        required: true

env:
  flutter_version: 3.41.8

# for testing studio and mls_api packages (both packages' tests depend on web and postgres running)
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: docker compose up -d --wait
      - name: sql
        run: |
          sudo apt-get install -y postgresql-client
          PGPASSWORD=eighty4 psql -h localhost -U eighty4 -f sql/v001-init-schema.sql eighty4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: 'stable'
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: pnpm/action-setup@v6
        with:
          cache: true
      - run: pnpm i
      - name: web
        run: |
          pnpm dev &
          sleep 5
        working-directory: web
      - name: playwright install
        run: pnpm exec playwright install --with-deps
        working-directory: packages/create_auth_token
      - name: test
        run: flutter test
        working-directory: ${{ inputs.flutter_package }}
