name: Package mls_api CI

on:
  push:
    branches: [ main ]
    paths:
      - packages/api_client/**
  pull_request:
    branches: [ main ]
  workflow_call:

env:
  flutter-version: 3.22.0

jobs:
  verified:
    runs-on: ubuntu-22.04
    needs:
      - analyze
      - format
      - test
    steps:
      - run: echo "Say! I like green builds and ham!"

  analyze:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter-version }}
          channel: 'stable'
      - name: analyze
        run: flutter analyze
        working-directory: packages/api_client

  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter-version }}
          channel: 'stable'
      - name: format
        run: dart format lib test --set-exit-if-changed
        working-directory: packages/api_client

  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter-version }}
          channel: 'stable'
      - name: test
        run: flutter test
        working-directory: packages/api_client
