name: Package mls_api CI

on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/mls_api.yml
      - packages/api_client/**
      - packages/create_auth_token/**
      - web/src/lib/data/**
      - web/src/routes/api/**
      - web/src/hooks.server.ts
      - pnpm-lock.yaml
  pull_request:
    branches: [ main ]

env:
  flutter_version: 3.27.1

jobs:

  verified:
    runs-on: ubuntu-22.04
    needs:
      - flutter_ci
      - test
    steps:
      - run: echo "Say! I like green builds and ham!"

  flutter_ci:
    uses: ./.github/workflows/flutter_verify.yml
    with:
      flutter_package: packages/api_client
      skip_test: true

  test:
    uses: ./.github/workflows/flutter_integration_test.yml
    with:
      flutter_package: packages/api_client
