name: Studio CI

on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/studio.yml
      - packages/api_client/**
      - packages/create_auth_token/**
      - studio/**
      - pnpm-lock.yaml
  pull_request:
    branches: [ main ]

env:
  flutter_version: 3.27.1

jobs:

  verified:
    runs-on: ubuntu-22.04
    needs:
      - flutter_ci
      - build_web
      - test_studio
    steps:
      - run: echo "I just want to break the build"

  flutter_ci:
    uses: ./.github/workflows/flutter_verify.yml
    with:
      flutter_package: studio
      skip_test: true

  build_web:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          path: mls
      - uses: actions/checkout@v4
        with:
          repository: eighty4/libtab
          path: libtab
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: 'stable'
      - name: build web
        run: flutter build web
        working-directory: mls/studio

  test_studio:
    uses: ./.github/workflows/flutter_integration_test.yml
    with:
      flutter_package: studio
