name: Web CI

on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/web.yml
      - packages/api_client/**
      - web/**
      - pnpm-lock.yaml
  pull_request:
    branches: [ main ]

jobs:

  verified:
    runs-on: ubuntu-latest
    needs:
      - e2e
      - build
      - test
      - typecheck
    steps:
      - run: echo "Take me down to the paradise city!"

  e2e:
    uses: ./.github/workflows/web_e2e.yml

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
      - run: pnpm i
      - name: vite
        run: pnpm build
        working-directory: web

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose up -d --wait
      - name: sql
        run: |
          sudo apt-get install -y postgresql-client
          PGPASSWORD=eighty4 psql -h localhost -U eighty4 -f sql/v001-init-schema.sql eighty4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
      - run: pnpm i
      - name: vitest
        run: pnpm test
        working-directory: web

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
      - run: pnpm i
      - name: svelte-check
        run: pnpm check
        working-directory: web
